[tool.poetry]
name = "aoc23"
version = "0.1.0"
description = "Advent of Code 2023"
authors = ["Michael Rook <michael.rook@live.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
